### ISSUE TITLE
No query executer factory registered for the "WebServiceQuery" language. is not a valid jrxml file:

### ISSUE THREAD

**Issue by tyler-tj** [acesseonline/pyreportjasper#102]
**Describe the bug**
Error when compiling a subreport that contains a WebServiceQuery.

Example WebServiceQuery in .jrxml:
<queryString language="WebServiceQuery">
  <![CDATA[{
    "getparameters" : {
      "request_id" : "$P{reportId}",
      "token" : "$P{token}"
    },
    "fieldsMap" : {
      "firstname" : "firstname",
      "lastname" : "lastname"
    },
    "fields" : [ {
      "name" : "firstname",
      "expression" : "firstname"
    }, {
      "name" : "lastname",
      "expression" : "lastname"
    } ],
    "options" : {
      "contentType" : "application/parameter",
      "rootPath" : "",
      "baseUrl" : ""
    },
    "headersMap" : { },
    "queryData" : "",
    "GETParameters" : {
      "request_id" : "$P{reportId}",
      "token" : "$P{token}"
    }
  }]]>
</queryString>

**To Reproduce**
1. Have Jasper .jrxml to compile with a WebServiceQuery
2. Use PyReportJasper to compile the .jrxml

**Screenshots**
ERROR org.apache.commons.digester.Digester - End event threw exception
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:278) ~[commons-beanutils-1.9.3.jar:1.9.3]
	at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:220) ~[commons-digester-2.1.jar:2.1]
	at org.apache.commons.digester.Rule.end(Rule.java:257) ~[commons-digester-2.1.jar:2.1]
	at org.apache.commons.digester.Digester.endElement(Digester.java:1345) [commons-digester-2.1.jar:2.1]
	at net.sf.jasperreports.engine.xml.JRXmlDigester.endElement(JRXmlDigester.java:266) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618) [?:?]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:947) [?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727) [?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898) [?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) [?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541) [?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) [?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) [?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [?:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224) [?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) [?:?]
	at org.apache.commons.digester.Digester.parse(Digester.java:1892) [commons-digester-2.1.jar:2.1]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:299) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:286) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:275) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:220) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:195) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:186) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
Caused by: net.sf.jasperreports.engine.JRRuntimeException: No query executer factory registered for the "WebServiceQuery" language.
	at net.sf.jasperreports.engine.util.JRQueryExecuterUtils.getExecuterFactory(JRQueryExecuterUtils.java:103) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.design.JRDesignDataset.queryLanguageChanged(JRDesignDataset.java:1240) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	at net.sf.jasperreports.engine.design.JRDesignDataset.setQuery(JRDesignDataset.java:691) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
	... 28 more
Error at C:\Users\tli\Projects\saas-gsked\jasper\template_export\resources\reports\Invoice_standard_template_files\pyreportjasper-Bill_Table.jrxml
Error compile file: input file: net.sf.jasperreports.engine.JRException: org.xml.sax.SAXParseException; lineNumber: 130; columnNumber: 17; Error at line 130 char 17: No query executer factory registered for the "WebServiceQuery" language. is not a valid jrxml file:

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8
 - Library version: latest
 - Java version: 16

**Jaspersoft Studio (please complete the following information):**
 - Version 6.16

**Comment by tyler-tj** [comment]
Any thoughts concerning this issue?

**Comment by jadsonbr** [comment]
@tyler-tj Data Adapter of type WebService not yet implemented
