### ISSUE TITLE
Error while loading available fonts

### ISSUE THREAD

**Issue by jmarco** [acesseonline/pyreportjasper#119]
ERROR net.sf.jasperreports.engine.util.JRStyledTextParser - Error while loading available fonts

** python
    Version 3.8.10

** pyreportjasper
    - Version 2.1.2

** JPype1
    - Version 1.3.0

** java - version
    openjdk version "11.0.13" 2021-10-19
    OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
    OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Jaspersoft Studio (please complete the following information):**
 - Version 6.16.0

Error
12:03:13.825 [main] ERROR net.sf.jasperreports.engine.util.JRStyledTextParser - Error while loading available fonts
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'isTrue': Instantiation of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.util.ObjectUtils.unwrapOptional(Ljava/lang/Object;)Ljava/lang/Object;
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:974) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:848) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:574) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:514) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:477) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:471) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at net.sf.jasperreports.extensions.SpringExtensionsRegistry.findExtensionBeanNames(SpringExtensionsRegistry.java:112) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.extensions.SpringExtensionsRegistry.getExtensionBeanNames(SpringExtensionsRegistry.java:96) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.extensions.SpringExtensionsRegistry.getExtensions(SpringExtensionsRegistry.java:69) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:134) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.DefaultJasperReportsContext.getExtensions(DefaultJasperReportsContext.java:277) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.repo.RepositoryUtil.getServices(RepositoryUtil.java:89) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.repo.RepositoryUtil.findInputStream(RepositoryUtil.java:190) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.repo.RepositoryUtil.getInputStreamFromLocation(RepositoryUtil.java:172) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontExtensions(SimpleFontExtensionHelper.java:186) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.ensureFontExtensions(FontExtensionsRegistry.java:93) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.getExtensions(FontExtensionsRegistry.java:57) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:134) ~[jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:116) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:156) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074) [jasperreports-6.16.0.jar:6.16.0-48579d909b7943b64690c65c71e07e0b80981928]
Caused by: java.lang.NoSuchMethodError: org.springframework.util.ObjectUtils.unwrapOptional(Ljava/lang/Object;)Ljava/lang/Object;
        at org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:194) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.BeanWrapperImpl.setWrappedInstance(BeanWrapperImpl.java:153) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.AbstractNestablePropertyAccessor.setWrappedInstance(AbstractNestablePropertyAccessor.java:183) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.AbstractNestablePropertyAccessor.<init>(AbstractNestablePropertyAccessor.java:122) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.BeanWrapperImpl.<init>(BeanWrapperImpl.java:103) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        ... 28 more

**Comment by jadsonbr** [comment]
This error is usually caused by using a font that is not installed in OS.

**Comment by jmarco** [comment]
SOLVED

Uninstall pyreportjasper

and install with

pip3 install git+https://github.com/acesseonline/pyreportjasper.git
