### ISSUE TITLE
Error in Jpype

### ISSUE THREAD

**Issue by aachiary** [acesseonline/pyreportjasper#127]
Hi, I'm having trouble to compile a JSON based report after getting an .exe of my application with cx_Freeze. When I use it with python command there is no problem.
The error I get is:

Traceback (most recent call last):
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python39\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python39\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "aprobar_factura.py", line 25, in <module>
  File "D:\Python-proj\loffreda-service\factura.py", line 108, in imprimir
    pyreportjasper.compile(write_jasper=True)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python39\lib\site-packages\pyreportjasper\pyreportjasper.py", line 130, in compile
    raise error
NameError: Error compile file: java.lang.ClassNotFoundException: org.jpype.classloader.DynamicClassLoader

I got it with JPype 1.3 and 1.4
Thanks!

**Comment by jadsonbr** [comment]
pyreportjasper has not been tested to run on standalone Python script executables. Try to check the cx_Freeze limitations with JPype and also try to check if the library jars are going along.

**Comment by jadsonbr** [comment]
Closed due to lack of interaction
