### ISSUE TITLE
NameError: Error fill report: No JVM shared library file (jvm.dll) found

### ISSUE THREAD

**Issue by Deepak-1D** [acesseonline/pyreportjasper#129]
When I try to run the example code I got this error. But I already have JDK in my machine.

```Traceback (most recent call last):
  File "d:\rigelsoft\curd_fastapi\jasper_t\pyjas.py", line 30, in <module>
    advanced_example_using_database()
  File "d:\rigelsoft\curd_fastapi\jasper_t\pyjas.py", line 28, in advanced_example_using_database
    pyreportjasper.process_report()
  File "D:\rigelsoft\curd_fastapi\fastenv\lib\site-packages\pyreportjasper\pyreportjasper.py", line 182, in process_report
    raise error
NameError: Error fill report: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable `properly.

**Comment by erparthchauhan** [comment]
setup the java_home environment you'll get this error sorted in no time.

**Comment by jadsonbr** [comment]
@Deepak-1D  You need to set the java environment variables correctly. Here is a link that may help you

[Setting JAVA_HOME environment variables](https://confluence.atlassian.com/confbr1/configurando-a-variavel-java_home-no-windows-933709538.html)

**Comment by jadsonbr** [comment]
Closed due to lack of interaction
