### ISSUE TITLE
Error occurred during initialization of VM

### ISSUE THREAD

**Issue by InitialDW** [acesseonline/pyreportjasper#130]
I'm having problem with the following error. Please help.

`java.lang.UnsupportedClassVersionError: org/update4j/DynamicClassLoader : Unsupported major.minor version 53.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:278)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2234)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2220)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1494)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1474)`

And here's my java -version output
![image](https://user-images.githubusercontent.com/10242561/193379058-2dd96297-ca14-4ead-9151-c1f443a71df8.png)

**Comment by InitialDW** [comment]
Nevermind.. I was being an idiot.. turns out it needs Java 9 or up to work, who'd knew...

![image](https://user-images.githubusercontent.com/10242561/193384028-f2f1551e-c87e-417d-9fd5-ad263b0d203f.png)
