### ISSUE TITLE
Cannot get JSON to process correctly into report.

### ISSUE THREAD

**Issue by bdallen** [acesseonline/pyreportjasper#179]
**Describe the bug**
Getting the following error.

python test.py
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "org.update4j.DynamicClassLoader"). To use archived non-system classes, this property must not be set
Traceback (most recent call last):
  File "E:\dev\...\...\reports\test.py", line 27, in <module>
    compiling()
  File "E:\dev\...\...\reports\test.py", line 25, in compiling
    pyreportjasper.process_report()
  File "E:\dev\...\venv\lib\site-packages\pyreportjasper\pyreportjasper.py", line 192, in process_report
    raise error
NameError: Error fill report: Erro fill internal: net.sf.jasperreports.engine.JRException: Unable to get value for JSON field "LineTotalExTax" of class java.lang.Float.

**To Reproduce**
Run the test.py file in the attached ZIP file along with the report

**Expected behavior**
Report generates to a PDF

**Screenshots**
Runs file in the Studio
![image](https://github.com/user-attachments/assets/10afea11-3cee-4bcc-b8d6-0aca440e12e2)

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Python version 3.10
 - Library version 2.1.4
 - Java version openjdk 17.0.7 2023-04-18 LTS

**Jaspersoft Studio (please complete the following information):**
 - Version 7.0 using 6.20.6 Version Compatability when saving

**Additional context**

**Comment by bdallen** [comment]
Hi All,

As an update, I changed to XML and it works fine, something is broken with the JSON side.

**Comment by bdallen** [comment]
Shifted to XML
