### ISSUE TITLE
error while installing pyreportjapser library in ec2 linux

### ISSUE THREAD

**Issue by gholakemohit** [acesseonline/pyreportjasper#81]
$ sudo pip3 install pyreportjasper
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pyreportjasper
  Downloading https://files.pythonhosted.org/packages/2a/1f/c463cdf4097e59a4c218e5b079770c310d00f127c6522a82369865da26a0/pyreportjasper-2.1.2-py3-none-any.whl (181.1MB)
    99% |████████████████████████████████| 181.1MB 34.9MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 86, in dumps
    data, separators=(",", ":"), sort_keys=True,
  File "/usr/lib64/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
MemoryError

**Comment by jadsonbr** [comment]
This problem is not linked to the library directly, but with your machine on ec2. Follow the link with possible resolution.

[https://aws.amazon.com/pt/premiumsupport/knowledge-center/ec2-memory-swap-file/](https://aws.amazon.com/pt/premiumsupport/knowledge-center/ec2-memory-swap-file/)

**Comment by gholakemohit** [comment]
ok
